# Generated by Django 5.0.2 on 2024-02-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('text_content', models.TextField(blank=True)),
                ('json_data', models.JSONField(blank=True)),
            ],
        ),
    ]
